using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Logout : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        Session["Giris"] = "";
        Session["ID"] = "";
        Session["KullAdi"] = "";
        Session["KullaniciKodu"] = "";
        Session["Name"] = "";
        Session["Departman"] = "";
        Session["Depo"] = "";
        Session["Yetki"] = "";
        Session["GirisTarihi"] = "";
        Session["TalepDurum"] = "";
        Session["Sorgu"] = "";
        Session["TeklifTalepIDleri"] = "";
        Session["TeklifOdemePlani"] = "";
        Session["TeklifCariHesap"] = "";
        Session["idariTalepID"] = "";
        Session["idariBirimFiyat"] = "";
        Session["idariFirma"] = "";
        Session["idariEvrakNo"] = "";
        Session["idariKullanilacakYer"] = "";
        Session["idariMiktar"] = "";
        Session["idariMalAdi"] = "";
        Session["idariTalepEden"] = "";
        Session["idariTarih"] = "";
        Session["idariTutar"] = "";
        Session["ihtiyacTalepID"] = "";
        Session["ihtiyacKullanilacakYer"] = "";
        Session["ihtiyacEvrakNo"] = "";
        Session["ihtiyacSiparisNo"] = "";
        Session["ihtiyacMalKodu"] = "";
        Session["ihtiyacMalAdi"] = "";
        Session["ihtiyacDepartmanAdi"] = "";
        Session["ihtiyacTarih"] = "";
        Session["ihtiyacMiktar"] = "";
        Session["ihtiyacBirim"] = "";
        Session["ihtiyacTarih"] = "";
        Session["ihtiyacMalAdi"] = "";
        Session["ihtiyacAciklama"] = "";
        Session["ihtiyacCarisi"] = "";
        Session["TeknikTalepID"] = "";
        Session["TeknikBirimFiyat"] = "";
        Session["TeknikFirma"] = "";
        Session["TeknikEvrakNo"] = "";
        Session["TeknikKullanilacakYer"] = "";
        Session["TeknikMiktar"] = "";
        Session["TeknikMalAdi"] = "";
        Session["TeknikTalepEden"] = "";
        Session["TeknikTarih"] = "";
        Session["TeknikTutar"] = "";
        Session["StokCikisTalepIDleri"] = "";
        Session["TalepEvrakNumaralari"] = "";
        Session["MalKodlari"] = "";
        Session["Miktarlar"] = "";
        Session["Kdvmiz"] = "";
        Session["MalAdlari"] = "";
        Session["TalepIDler"] = "";
        Session["StokluDepartmanKodu"] = "";
        Session["DepartmanKodu"] = "";
        Session["KullaniciKodu"] = "";
        Session["Yetki"] = "";
        Session["KullaniciKodu"] = "";
        Session["DepartmanKodu"] = "";
        Session["AltDepartmanKodu"] = "";
        Session["Yetki"] = "";
        Session["KullAdi"] = "";
        Session["StokluDepartmanKodu"] = "";
        Session["izinAyari"] = "";
        Session["izinYetki"] = "";
        Session["SiparisTalepID"] = "";
        Session["SiparisEvrakNo"] = "";
        Session["SiparisTalepSiparisNo"] = "";
        Session["SiparisMalKodu"] = "";
        Session["SiparisMalAdi"] = "";
        Session["SiparisBirim"] = "";
        Session["SiparisTarih"] = "";
        Session["SiparisMiktar"] = "";
        Session["SiparisBirimFiyat"] = "";
        Session["SiparisKdv"] = "";
        Session["SiparisTutar"] = "";
        Session["SiparisTalepEden"] = "";
        Session["HomePage"] = "";
        Session["StokKartiAra"] = "";
        Session["IhtiyacArama"] = "";
        Session["Talepler"] = "";
        Session["Formlar"] = "";
        Session["idariKisim"] = "";
        Session["TeknikKisim"] = "";
        Session["ihtiyacPusulasi"] = "";
        Session["StokCikisFormu"] = "";
        Session["StokCikisHareketi"] = "";
        Session["SiparisFormu"] = "";
        Session["FaxCekimi"] = "";
        Session["Tanimlar"] = "";
        Session["Tanimlamalar"] = "";
        Session["StokTanimlama"] = "";
        Session["KullaniciTanimi"] = "";
        Session["Aramalar"] = "";

        Response.Redirect("Login.aspx");
    }
}